FROM arm32v6/alpine:3.21 AS build
RUN apk add --no-cache ca-certificates

FROM scratch

ENTRYPOINT ["/usr/bin/cleanup-stale-branches-action"]

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

COPY bin/cleanup-stale-branches-action /usr/bin/cleanup-stale-branches-action
